name: generate-graph

on:
  pull_request:
  workflow_dispatch:

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set environment variables
        run: |
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
          echo "ORG_NAME=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "PULL_REQUEST_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: Install packages
        run: npm install
      - name: Run generateGraph.js
        run: node ./.github/scripts/generateGraph.js
        env:
          PULL_REQUEST_NUMBER: ${{ env.PULL_REQUEST_NUMBER }}
          REPO_NAME: ${{ env.REPO_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive result
        uses: actions/upload-artifact@v2
        with:
          name: graph-svg
          path: ./graph.svg
